Release/1.0.0
Leboroz/Pollution-app pull request #1
Opened 2022-03-11 21:57 UTC by Leboroz

# BallheadApp [LIVE](https://leboroz-ballhead.netlify.com)

![finish](https://media.tenor.com/images/f977004881573869003cc7d82b3dc610/tenor.gif)

## Learning objectives

- Use React documentation.
- Use React components.
- Use React props.
- Use React Router.
- Connect React and Redux.
- Handle events in a React app.
- Write integration tests with a React testing library.
- Use styles in a React app.
- Use React life cycle methods.
- Apply React best practices and language style guides in code.
- Use store, actions, and reducers in React.

>This React capstone project is about building a mobile web application to check a list of metrics (numeric values) that I created making use of React and Redux.

### pages: 

- one page with a list of items that could be filtered by some parameters; in the example below, it's a list of metrics that can be filtered by the country.

- one page for the item details; in the example, the detail page for Czech Republic cities with a number of views.

### Interactions

#### Home page

- When the page loads, the webapp shows the list of categories that could be filtered out by some parameter, for example by the category name.
- Along with the category name, you will display some numeric values per category that come from the API.
- When the user clicks (or taps) on a category item, the application navigates to the details page.

#### Details page

- In the details page, the webapp retrieves data from the API to show detailed data in the category.
- When the user clicks on the "Back" button (<), the user navigates to the home page.

2022-03-11 22:15 UTC, bimbolabuari requested changes
Hi @Leboroz, 

You have done a good job so far 🚀  

## Highlights 🎉 
- Gives appropriate credit to [Nelson Sakwa](https://www.behance.net/sakwadesignstudio) the [author of the original design](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs))
- Deploys application using Netlify
- The project contains a `Home` page and a `Detail` page

There are some issues that you still need to work on to go to the next project but you are almost there! 🎉 


## Required Changes ♻️
- [x] Kindly add a video presentation that contains a demo of the project, highlighting all the project features

- [ ] Check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

--------


_Reviewed by  @bimbolabuari_

2022-03-11 22:15 UTC, bimbolabuari commented on src/pages/About.jsx
> +  );
Currently, the detail page isn't showing the country statistics as required.

![image](https://user-images.githubusercontent.com/66112760/157979319-38b2c345-7721-45b2-9254-66b12cda7d0a.png)

2022-03-12 19:57 UTC, moise10r requested changes
Hi @Leboroz,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## To Highlight :clap: 
- PR has a good title and summary. ✔️
- Professional README file. :heavy_check_mark:
- Good presentation video. ✔️ 
- Your app has been well deployed  ✔️ 
- Your app works as expected  I really appreciate +1: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏 💻  
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @moise10r when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-12 19:57 UTC, moise10r commented on README.md
- [ OPTIONAL] update the live demo in of your README file

2022-03-12 19:57 UTC, moise10r commented on src/pages/Home.jsx
> +  const [open, setOpen] = useState(false);
- [OPTIONAL] Kindly, you should follow these [design guidelines](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)), what if you move your title or name of the country to the left of your header section as show bellow :arrow_down: 

||  Original [design guidelines](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs))  ||
|-|-----------------------------------|-|
||![go1](https://user-images.githubusercontent.com/57562869/157501449-50bab51c-5494-447a-a950-0c1abbba504d.png)||

||![11111111111111](https://user-images.githubusercontent.com/57562869/158032898-c092d927-298b-4837-b04c-e58ef1059b0b.png)||

2022-03-12 20:39 UTC, bimbolabuari approved these changes
# Project Approved 🚀

Hi @Leboroz 🥇,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-12 20:41 UTC, closed without merging